apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: speedtest-job
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          containers:
          - name: speedtest
            image: lalx/speedtest-cli:latest
          restartPolicy: OnFailure
